site_name: crosszip
site_description: Iterating over all combinations from multiple iterables
site_url: https://indrajeetpatil.github.io/crosszip/
theme:
  name: material
repo_url: https://github.com/IndrajeetPatil/crosszip
repo_name: crosszip
site_author: IndrajeetPatil
markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      anchorlink: true
      anchorlink_class: "toclink"
  - pymdownx.snippets:
  - pymdownx.magiclink:
  - attr_list:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
