name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv python install
          uv sync --all-extras --dev

      - name: Build Docs
        run: uv run mkdocs build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: uv run mkdocs gh-deploy --force
