name: QA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qa:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pre-commit hooks
        run: .venv/bin/pre-commit run --all-files

      - name: Compute Coverage
        run: |
          .venv/bin/coverage run -m pytest tests/
          .venv/bin/coverage report --fail-under=95
          .venv/bin/coverage html
